export const tastesToSelect = [
  { id: "pasta", name: "Massas" },
  { id: "pizza", name: "Pizza" },
  { id: "hamburger", name: "Hamburguer" },
  { id: "sushi", name: "Sushi" },
  { id: "iceCream", name: "Sorvete" },
  { id: "coffee", name: "Café" },
  { id: "beer", name: "Cerveja" },
  { id: "glutenFree", name: "Sem Glúten" },
  { id: "bbq", name: "Churrasco" },
  { id: "vegan", name: "Vegano" },
  { id: "vegetarian", name: "Vegetariano" },
  { id: "fit", name: "Fit" },
  { id: "fastFood", name: "Fast Food" },
  { id: "dessert", name: "Sobremesa" },
];
