FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt gunicorn

COPY . .

EXPOSE 8080

ENV PORT=8080
ENV FLASK_APP=main.py
ENV FLASK_ENV=production
ENV PYTHONUNBUFFERED=1

CMD exec gunicorn --bind :$PORT "main:create_app()" --workers 1 --threads 8 --timeout 0 --log-level debug
