name: Deploy to Cloud Run

on:
  push:
    branches:
      - master
    paths:
      - 'api/**'

env:
  PROJECT_ID: thinking-device-436722-v0
  REGION: us-central1
  SERVICE_NAME: irecipes-api

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Authorize Docker push
      run: gcloud auth configure-docker

    - name: Build and Push Container
      run: |
        cd api
        docker build -t gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }} .
        docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}

    - name: Create env-vars file
      run: |
        echo "MONGO_URI=${{ secrets.MONGO_URI }}" > env-vars.txt
        echo "GOOGLE_CLOUD_CREDENTIALS=$(echo '${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}' | base64 -w 0)" >> env-vars.txt

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ${{ env.SERVICE_NAME }} \
          --image gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }} \
          --platform managed \
          --region ${{ env.REGION }} \
          --allow-unauthenticated \
          --env-vars-file env-vars.txt
